apiVersion: v1
data:
  password: c29tZS1zZWNyZXQ=
  username: a2V5Y2xvYWs=
kind: Secret
metadata:
  name: keycloak-user
  namespace: security-db
type: kubernetes.io/basic-auth
---
#apiVersion: v1
#data:
#  password: dU4zaTFIaDBiWWJDYzRUeVZBYWNCaG1TemdxdHpxeG1PVmpBbjBRSUNoc0pyU211OVBZMmZ3MnE4RUtLTHBaOQ==
#  username: cG9zdGdyZXM=
#kind: Secret
#metadata:
#  name: cluster-example-superuser
#type: kubernetes.io/basic-auth
---
#apiVersion: v1
#kind: Secret
#metadata:
#  name: backup-creds
#data:
#  ACCESS_KEY_ID: a2V5X2lk
#  ACCESS_SECRET_KEY: c2VjcmV0X2tleQ==
---